'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createSampleRepository, IP_LIMIT, DAILY_LIMIT, GUEST_SECONDS, QUESTION_LIMIT, TRIAL_SECONDS } = require('../sample-materials-service');
function fakeDb() {
  const data = new Map();
  function ref(path) { return { id: path.split('/').at(-1), path, async get() { return snapshot(this); }, async set(value) { data.set(path, value); }, async update(value) { data.set(path, { ...data.get(path), ...value }); } }; }
  function snapshot(doc) { return { exists: data.has(doc.path), id: doc.id, data: () => data.get(doc.path) }; }
  const db = { collection(name) { return { doc(id) { return ref(name + '/' + id); } }; }, async runTransaction(task) { return task({ get: async doc => snapshot(doc), set(doc, value) { data.set(doc.path, value); }, update(doc, value) { data.set(doc.path, { ...data.get(doc.path), ...value }); } }); } };
  return { db, data };
}
test('guest tokens are random and persisted only as hashes with a finite expiry', async () => { const h = fakeDb(), repository = createSampleRepository(h.db), guest = await repository.open('math', '203.0.113.1', 1000, 'sheet'); assert.match(guest.token, /^[a-f0-9]{64}$/); assert.equal(guest.expiresAt, 1000 + GUEST_SECONDS * 1000); const entries = [...h.data].filter(([path]) => path.startsWith('sampleMaterialsSessions/')); assert.equal(entries.length, 1); assert.ok(!entries[0][0].includes(guest.token)); assert.ok(!JSON.stringify([...h.data]).includes('203.0.113.1')); assert.equal(entries[0][1].worksheetId, 'sheet'); });
test('public trial allocation enforces both IP and centre-wide quotas before creating a session', async () => { const h = fakeDb(), repository = createSampleRepository(h.db); for (let i = 0; i < IP_LIMIT; i++) await repository.open('math', 'one-ip', 1000, 'sheet'); await assert.rejects(repository.open('math', 'one-ip', 1000, 'sheet'), error => error.status === 429); const global = [...h.data].find(([path]) => path.includes('/_global_'))[0]; h.data.set(global, { starts: DAILY_LIMIT }); await assert.rejects(repository.open('science', 'different-ip', 1000, 'sheet'), error => error.status === 429); assert.equal([...h.data].filter(([path]) => path.startsWith('sampleMaterialsSessions/')).length, IP_LIMIT); });
test('tokens are subject-bound, expire server-side and cannot overspend question budget', async () => { const h = fakeDb(), repository = createSampleRepository(h.db), guest = await repository.open('math', 'one-ip', 1000, 'sheet'); await assert.rejects(repository.use(guest.token, 'science', 1001, 'ask'), error => error.status === 401); for (let i = 0; i < QUESTION_LIMIT; i++) await repository.use(guest.token, 'math', 1001, i % 2 ? 'check' : 'ask'); await assert.rejects(repository.use(guest.token, 'math', 1001, 'ask'), error => error.status === 429); await assert.rejects(repository.use(guest.token, 'math', guest.expiresAt, 'questions'), error => error.status === 401); });
test('live reservation records a server deadline and permits only one paid trial', async () => { const h = fakeDb(), repository = createSampleRepository(h.db), trial = await repository.open('science', 'one-ip', 1000, 'sheet'); const guest = await repository.use(trial.token, 'science', 1100, 'start'); assert.equal(guest.liveExpiresAt, 1100 + TRIAL_SECONDS * 1000); const snap = await repository.find(trial.token, 'science'); assert.equal(snap.pending, true); assert.equal(snap.liveStarts, 1); await repository.activate(guest, 'live-opaque'); assert.equal((await repository.find(trial.token, 'science')).sessionId, 'live-opaque'); await assert.rejects(repository.use(trial.token, 'science', 1200, 'start'), error => error.status === 429); });
test('failed unpaid start refunds only its reserved voice trial', async () => { const h = fakeDb(), repository = createSampleRepository(h.db), trial = await repository.open('science', 'one-ip', 1000, 'sheet'); const guest = await repository.use(trial.token, 'science', 1100, 'start'); await repository.release(guest); assert.equal((await repository.find(trial.token, 'science')).liveStarts, 0); const retry = await repository.use(trial.token, 'science', 1200, 'start'); assert.equal(retry.liveStarts, 0); });
